### ISSUE TITLE
Sending stats admin URL doesn't work with Django 1.10

### ISSUE THREAD

**Issue by a115** [django-ses/django-ses#104]
Using the latest django_ses==0.8.0 from Pip. 

The django_ses urls.py include the following import:
    `from django.conf.urls.defaults import patterns, url`

With Django 1.10, this gives an `ImportError: No module named defaults`. This is because the code fails to import `patterns`, and then wrongly assumes that we're on Django < 1.4, which isn't the case.

**Comment by owenfi** [comment]
Would love to see a new release of this package now that django 1.10 is released and the fix is merged.

**Comment by crearc** [comment]
This commit already removes patterns: https://github.com/django-ses/django-ses/commit/411d16fa6cc849ebdca1936f996a73b06bcb7d6e

You can use master and it works fine, but I'm hoping @pcraciunoiu will just bump the version.

**Comment by crearc** [comment]
@a115 @owenfi 0.8.1 should work for yah.

**Comment by crearc** [comment]
So that wasn't the only fix that needed to be made to fix the admin. Made a PR (https://github.com/django-ses/django-ses/pull/107) for fixing the admin.
