### ISSUE TITLE
Drop support for earlier versions of Django

### ISSUE THREAD

**Issue by alasdairnicol** [django-ses/django-ses#105]
The changes in 14a7c79f453072936b1c50544db6a9cb8fb4e862 are not compatible with Django 1.6 and earlier (Using a list instead of `patterns` in Django 1.7 is undocumented but it will work).

However, the  tox file still tests for Django 1.3-1.7.

Would you accept a patch that dropped support for Django 1.7 and earlier? Django 1.8 LTS is currently the oldest supported version. Django 1.7 and earlier have not been supported since Django 1.9 was released in December 2015.

**Comment by pcraciunoiu** [comment]
Absolutely, patches are welcome :)
