### ISSUE TITLE
SNS Bounce handler issue with Python3

### ISSUE THREAD

**Issue by someidiot** [django-ses/django-ses#112]
In Python 3, Django 1.10 the handle_bounce() view errors processing the request body:

notification = json.loads(raw_json)
Exception Type: TypeError at /ses/bounce/
Exception Value: the JSON object must be str, not 'bytes'

The raw_json = request.body should probably be raw_json = request.body.decode('utf-8')

Also, it would be VERY appreciated if there were actual documentation for this SNS subscription feature,

**Comment by pcraciunoiu** [comment]
Hi @someidiot -- I've been on and off on this project. Does this address your concern for SNS? https://github.com/django-ses/django-ses#ses-event-monitoring-with-configuration-sets

As for `handle_bounce`, if you can submit a Pull Request to address the issue, I'd welcome it!

**Comment by quarkness** [comment]
https://github.com/quarkness/django-ses/tree/bytes-as-bytes fixes the `handle_bounce` issue for me in Python 3.6.

**Comment by pcraciunoiu** [comment]
@quarkness if you could write a test and open a PR, I can get your fix merged in!

**Comment by alexandernst** [comment]
I think this can get closed? @pcraciunoiu
