### ISSUE TITLE
No Python3 installables

### ISSUE THREAD

**Issue by astronouth7303** [django-ses/django-ses#114]
Only the "binary" wheel for Python 2 was uploaded to PyPI, making v0.8.2 uninstallable on Python3.

**Comment by camilonova** [comment]
Yes, please change pypi release to add support for python3

**Comment by whyscream** [comment]
The wheel release is also not usable with tools such as fpm (https://github.com/jordansissel/fpm). Please also upload a source version of the package (`python setup.py sdist`).

**Comment by camilonova** [comment]
@pcraciunoiu You should just use `python setup.py sdist upload`

Thanks

**Comment by pcraciunoiu** [comment]
OK I went ahead and did that. Please verify and we can close this if it's good now :+1:

**Comment by astronouth7303** [comment]
lgtm
