### ISSUE TITLE
Error messages state `US-EAST-1` when using `us-west-2`

### ISSUE THREAD

**Issue by paulhauner** [django-ses/django-ses#120]
I am attempting to send emails with this package, which I have used successfully in the past. I am getting an identity check failure referencing us-east-1 when I have set the region to us-west-2.

I have checked the value of `AWS_SES_REGION_NAME` at run-time, immediately before sending the email. It does equal `us-west-2`.

settings.py:
```
AWS_SES_REGION_NAME = 'us-west-2'
AWS_SES_REGION_DEVICE = 'email.us-west-2.amazonaws.com'
```

Error message from Django's stack trace:
```
SESAddressNotVerifiedError: 400 Email address is not verified.
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>MessageRejected</Code>
    <Message>Email address is not verified. The following identities failed the check in region US-EAST-1: alice@paulhauner.com, paul@paulhauner.com</Message>
  </Error>
  <RequestId>a0ee8dcf-39e2-11e7-a5c1-f3494eddd8b3</RequestId>
</ErrorResponse>
```

**Comment by ikcam** [comment]
Update your settings to:

```python
AWS_SES_REGION_NAME = 'us-west-2'
AWS_SES_REGION_ENDPOINT = 'email.us-west-2.amazonaws.com'
```

The `ENDPOINT` is the source of your issue.

**Comment by paulhauner** [comment]
Oh totally. Thank you so much!
