### ISSUE TITLE
django-ses is unable to use ECS task roles, uses instance role instead (boto3 required?)

### ISSUE THREAD

**Issue by dimaulupov** [django-ses/django-ses#124]
Probably because django-ses is not using boto3 it can't use IAM Roles for ECS tasks feature.
Whenever it tries to send email it uses role from instance profile instead.
And if instance is not allowed to access SES we get permission errors.

IAM Roles for Tasks are described here: [http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html)

django-amazon-ses is using boto3 and uses task role correctly.

To reproduce create ECS cluster without giving access to SES from instance role and then create ECS Service with role with SES access. Trying to send email with django-ses gives 403 error with explanation that instance role does not have access to SES.

**Comment by pcraciunoiu** [comment]
@dimaulupov I'd welcome a Pull Request to fix this if you're willing!

**Comment by cmc333333** [comment]
We can confirm that the 1.0 release of `django-ses` (which switched to `boto3`) can grab ECS metadata correctly.
