### ISSUE TITLE
Non-unicode log messages can break on sender name

### ISSUE THREAD

**Issue by efischer19** [django-ses/django-ses#137]
Hello! I work at edx.org, where we make use of this library to send bulk emails from educators to learners.

Recently, [we ran into an issue with some Spanish courses](https://openedx.atlassian.net/browse/EDUCATOR-1773). Specifically, [this logging statement](https://github.com/django-ses/django-ses/blob/v0.8.3.1/django_ses/__init__.py#L217-L222) causes a `UnicodeEncodeError` when `message.from_email` contains non-ascii characters. In our case, the `from_email` value is constructed as `{course_title} Course Staff <{some_valid_noreply_addr}>`, and for these courses, the titles contain accented vowels.

It's worth noting that the emails are sent without any issue, the only problem seems to be the logging statements as far as I can tell.

Here is a fairly minimal recreation taken from a pdb session I just ran:

```
(Pdb) from_addr
u'"\xf3\xf3\xf3\xf3\xf3\xf3\xf3\xf3\xf3\xf3\xf3\xf3\xf3\xf3\xf3" Course Staff <asdasd-no-reply@example.com>'
(Pdb) print "send_messages.sent from='{}'".format(from_addr)
*** UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-15: ordinal not in range(128)
(Pdb) print u"send_messages.sent from='{}'".format(from_addr)
send_messages.sent from='"óóóóóóóóóóóóóóó" Course Staff <asdasd-no-reply@example.com>'
```

Would there be any drawback to making all log messages unicode by default? I'm happy to put together a PR if you'd like.

Thanks, and have a great weekend!

**Comment by pcraciunoiu** [comment]
@efischer19 make sure to test this on python 3. I haven't looked into how it affects that, but there should be some good examples of cross-version handling on the internets.

Yay edx! I worked at Minerva and met someone who worked there :)
