### ISSUE TITLE
Request Confirmation: TypeError at /ses/bounce/ a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by FahadAlbukhari** [django-ses/django-ses#151]
Monitoring email status using Amazon Simple Notification Service (Amazon SNS)

SNS dashboard --->  Subscriptions ---> Endpoint ---> /ses/bounce/  ---> Request Confirmation

When request confirmation I get this error:

Internal Server Error: /ses/bounce/

TypeError at /ses/bounce/
a bytes-like object is required, not 'str'

Traceback:

File "/home/ubuntu/www/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
 35.             response = get_response(request)

File "/home/ubuntu/www/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
 128.                 response = self.process_exception_by_middleware(e, request)

File "/home/ubuntu/www/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
 126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/ubuntu/www/lib/python3.6/site-packages/django/views/decorators/csrf.py" in wrapped_view
 54.         return view_func(*args, **kwargs)

File "/home/ubuntu/www/lib/python3.6/site-packages/django/views/decorators/http.py" in inner
 40.             return func(request, *args, **kwargs)

File "/home/ubuntu/www/lib/python3.6/site-packages/django_ses/views.py" in handle_bounce
 199.             not utils.verify_bounce_message(notification)):

File "/home/ubuntu/www/lib/python3.6/site-packages/django_ses/utils.py" in verify_bounce_message
 189.     return verifier.is_verified()

File "/home/ubuntu/www/lib/python3.6/site-packages/django_ses/utils.py" in is_verified
 59.             pkey.verify_update(sign_bytes)

File "/home/ubuntu/www/lib/python3.6/site-packages/M2Crypto/EVP.py" in verify_update
 249.         return m2.verify_update(self.ctx, data)

Exception Type: TypeError at /ses/bounce/
Exception Value: a bytes-like object is required, not 'str'
Request information:
USER: AnonymousUser

**Comment by pcraciunoiu** [comment]
Hi @FahadAlbukhari could you test that this fixes your issue?
https://github.com/django-ses/django-ses/pull/152

**Comment by pcraciunoiu** [comment]
You can do that with a `pip install git+https://github.com/django-ses/django-ses.git@fix/bytes`

**Comment by pcraciunoiu** [comment]
Try inserting breakpoints above those lines `import pdb; pdb.set_trace()` on a line by itself and then you can `print(object)` to send me the value here, for example for `notification` in `views.py` line `199`.

Send me more information, as much as you can think of that would be helpful, about what type of setup is producing this.

It's either that, or you try to fix it yourself. That would be great!!!

**Comment by FahadAlbukhari** [comment]
I sent "notification"  to my email an I got this

{'Type': 'SubscriptionConfirmation', 'MessageId': '5277eacc-e061-4b3f-ba37-5ee4b0okm15c', 'Token': '2336410okmfb687f5d51e6e241da92fd739f58c04b56d83937b3f48909c452c56c44763e75a426ac0423b15d77003299b513be879e527167f6287bdcda37258c115e319413facc80fd03526d8df05f0e0f52d187211c58f9876b94eaa403830dff8fa100367c6a906d6db718c35ec1df', 'TopicArn': 'arn:aws:sns:eu-west-1:868362952999:dj', 'Message': 'You have chosen to subscribe to the topic arn:aws:sns:eu-west-1:868362952999:dj.\nTo confirm the subscriptionDataBuilder, visit the SubscribeURL included in this message.', 'SubscribeURL': 'https://sns.eu-west-1.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:eu-west-1:868362952999:dj&Token=2336412f37fb680okm51e6e241da92fd739f58c04b56d83937b3f48909c452c56c44763e75a426ac0423b15d77003299b513be879e527167f6287bdcda37258c115e319413facc80fd03526d8df05f0e0f52d187211c58f9876b94eaa403830dff8fa100367c6a906d6db718c35ec1df', 'Timestamp': '2018-06-02T04:39:14.889Z', 'SignatureVersion': '1', 'Signature': 'a2HzSgAY5j5NIYcPEY5fO24Ui0okmnLk38w7btpIIZQs2YJWKtIr3qbn74QDnWDSyCBLRz5hE/jAZAwtW5EyBFo8A5SNIi/5M1cb55LEw+2tP0LARsl8wLsfugYuS50pD+0DkKDCRd6yj9siAp7x2sr1SPegamL7JRHSFpjYz0N3SJycTGzliAaFeFf7O9KEpiMVE7vJaV4FFzH2fZ2fT+ReZNDJRUIAweaEDg8Fdb+RC/Fo2UmmLWetubprbechrgVzpGJ+kEFj4rmr0t1/Cug0NOnUu+vg9adHDcsTcD7tKmQ4BmjbDqxIxW88ZzaQkGXESZPneyRqyVulfpVnIw==', 'SigningCertURL': 'https://sns.eu-west-1.amazonaws.com/SimpleNotificationService-eaea6120e9ijn12e88dcd8bcbddca752.pem'}

**Comment by Dineshs91** [comment]
@pcraciunoiu This worked for me 
`pip install -e git+git://github.com/django-ses/django-ses.git@fix/bytes#egg=django-ses`. 

Can #151 be merged and release a new version with this change ?
