### ISSUE TITLE
not verifying valid SNS notification messages

### ISSUE THREAD

**Issue by johnbyrne7** [django-ses/django-ses#157]
I am unable to verify valid SNS notifications.  I get error "Received unverified notification: Type: SubscriptionConfirmation".

I know the message is one from AWS, as I just sent it from AWS console.

in debug, this sequence fails, since verify_result is set to 0
   verify_result = pkey.verify_final(signature)
   self._verified = verify_result == 1

i did capture these values, although I have replaced the actual ARN value with nnnn

p signature
'\x131=\x9dj\x94\xc6\xe0\xabHI\xbe8\xbc8\xda\xcb\x96/U\x830_\x1b\xb2\xb3\xe7\x87c\xef\x85\xbe@\x00\x9eW$\x85\xb9\xa2\xab\xa3\xb4A1\x1e6\xfd@\xefC\x12+\x95\x15\x0f\xc5\xbb\x1aU\xcdyN\xd5"\x0ecqj\xde\x9a\xe0\xcb\x9e/\x11F\xc6\xf0\x96\xe7\xb9\xd7*\xf8\xc5\x9e\xb3\xd1W\xe3\xbb\xa1\xfbi\x98\x9a\xe9\x9d\xf9D<z`V?\xcf\xeb\xb4\x89\xd6\xc0z\xd6cr\xb1\xbf\x07\xf43W\x87\x1ce\x93\xbdo\xb9\xebqqmG?|\x88\x19\x10\xc2\x9c\x9f/h]\r\x8f\xc5-\xcc\xaa\x9a\x90\xbfA\xa2\xb2\x8f\x94\xc3\x16B\x1bMv"\xf7\xee \x0fy\xef[R\'MD\xf4\x81\xfd\xf2\x83\xa3\xfc\x02f <\x19/aM!\xb2EQy\xbb\xec\xc6z[\xabK\xc4\xe9R\xd0\xc3<\x06X9\xea\'\xd1\xe9\xf5_\xf7H\xfd&\x95\xe4\xf9\x0e\xe5\x87W\xedK\xa1\x07\xc5\xe7\xe3\xd2\xe4\xff\x8f\xf5]Z/\xf1"\x1fc\x84\xe1\x9c\xc4iPq'

p sign_bytes
u'Message\nYou have chosen to subscribe to the topic arn:aws:sns:us-east-1:nnnnnnnnnn:email_bounce_tracking_dev.\nTo confirm the subscriptionDataBuilder, visit the SubscribeURL included in this message.\nMessageId\n585f4267-5b00-4171-973a-4f3deea39b83\nSubscribeURL\nhttps://sns.us-east-1.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-east-1:nnnnnnnnn:email_bounce_tracking_dev&Token=2336412f37fb687f5d51e6e241da92fd7d35f61183216b8b7e0e4dff5b6bac49daa15f063ffe229046e0ec4828e6a5dd6b9ee410ee677014bd3f73836c469af5d1f4f90d574e586d65b9ac1ece9a0210fdda8efd2c1257a5c65ef8f94390370c8571fe00813b8d0ef0df76ea65194c7f619d501c7cff0137a40f15310fa296c3\nTimestamp\n2018-08-14T17:00:12.552Z\nToken\n2336412f37fb687f5d51e6e241da92fd7d35f61183216b8b7e0e4dff5b6bac49daa15f063ffe229046e0ec4828e6a5dd6b9ee410ee677014bd3f73836c469af5d1f4f90d574e586d65b9ac1ece9a0210fdda8efd2c1257a5c65ef8f94390370c8571fe00813b8d0ef0df76ea65194c7f619d501c7cff0137a40f15310fa296c3\nTopicArn\narn:aws:sns:us-east-1:nnnnnnnnn:email_bounce_tracking_dev\nType\nSubscriptionConfirmation\n'

FYI, I am using HTTP as its my dev server, which may be a factor

**Comment by johnbyrne7** [comment]
i figured this out, but you should fix it..

I'm running on python 2.7, and I believe your to_bytes() function isn't correct.  as you can see above, sign_bytes is unicode, and it wont match the str signature.

I quick fixed utils by adding: 
     sign_bytes = sign_bytes.encode('utf-8')

after the check for valid sign_bytes in is_verified()

**Comment by pcraciunoiu** [comment]
That was broken in the last release I think. If you want to submit a PR, that'd be great @johnbyrne7

**Comment by pcraciunoiu** [comment]
Closed in #167.
