### ISSUE TITLE
"Email address is not verified" for verified email

### ISSUE THREAD

**Issue by Miserlou** [django-ses/django-ses#16]
TBH, I'm not sure where this bug is coming from, Boto, SES or my own configuration. 

Here it is though:

BotoServerError at /accounts/signup/

BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>MessageRejected</Code>
    <Message>Email address is not verified.</Message>
  </Error>
  <RequestId>9360bdd6-c549-11e0-82fb-b9b4121fdb69</RequestId>
</ErrorResponse>

$ ./manage.py ses_email_address -l
Fetching list of verified emails:
notifier@gun.io

Settings.py:
EMAIL_BACKEND = 'django_ses.SESBackend'
EMAIL_FROM = 'notifier@gun.io'
EMAIL_HOST_USER='notifier@gun.io'
DEFAULT_FROM_EMAIL='notifier@gun.io'
SERVER_EMAIL='notifier@gun.io'

Went through the notification confirmation email from Amazon.. so why the rejected message?

**Comment by anup36** [comment]
am also getting the same problem but in nodejs ... 


var ses = require('node-ses')
  , client = ses.createClient({ key: 'mykey', secret: 'mysecret',region: 'us-west-2', amazone:'email.us-west-2.amazonaws.com' });
 
// Give SES the details and let it construct the message for you.  
client.sendEmail({
   to: 'anup.panwar6@gmail.com'
 , from: 'anup.panwar36@gmail.com'
 , sender: 'anup.panwar36@gmail.com'
 , bcc: ['anup.panwar6@gmail.com']
 , subject: 'greetings'
 , message: 'your goes here'
 , altText: 'plain text'
}, function (err, data, res) {
 if(err){
		console.log(err);
	}
	else{
		console.log(data);
	}
});

**Comment by scknechaev** [comment]
Guys here is the solution
https://stackoverflow.com/questions/34879315/amazon-ses-email-address-is-not-verified/34879520#34879520
