### ISSUE TITLE
On email.send(), error 'tuple' object has no attribute 'encode'

### ISSUE THREAD

**Issue by wk0** [django-ses/django-ses#170]
email.send() works with:
`EMAIL_BACKEND = django.core.mail.backends.console.EmailBackend`
but not with the django_ses.SESBackend.

Using python3.7.2 and Django 2.1

**Comment by pcraciunoiu** [comment]
@wk0 if you want to take a stab at fixing and adding a test, that'd be awesome. This project is loosely maintained on my own time, as I'm not actively using it now, so I won't be able to get to this anytime soon unfortunately. But I welcome contributions!

**Comment by wk0** [comment]
Actually, turns out this was a problem with my AWS keys being read as a tuple, changing the formatting worked and everything is working as expected.
