### ISSUE TITLE
Track `requests` and `M2Crypto` as dependencies in an extras

### ISSUE THREAD

**Issue by ksze** [django-ses/django-ses#171]
`requests` and `M2Crypto` are required for bounce message verification in [`django_ses/utils.py`](https://github.com/django-ses/django-ses/blob/master/django_ses/utils.py). However those packages are not tracked as dependencies of `django-ses` and have to be installed explicitly by the user. Those packages are then added to requirements.txt or Pipfile. The user could add comments in `requirements.txt` or `Pipfile`, but the comments could be inadvertently wiped out by automation tooling (e.g. `pip freeze` or `pipenv install`). So it's easy, for example, to forget why `M2Crypto` was added in the first place, then the user removes it and bounce message handling starts failing, at which point it's a bit too late.

I would suggest tracking those packages as a `bounce` extras in [`setup.py`](https://github.com/django-ses/django-ses/blob/master/setup.py), like described here: https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

Users who would like to use the bounce handling can then do `pip install django-ses[bounce]`

**Comment by pcraciunoiu** [comment]
Hey @ksze, thanks for filing this issue and putting together details. If you'd like to contribute a PR to address this, that'd be great!

**Comment by ksze** [comment]
@pcraciunoiu 
Would you consider merging these two commits as well?
https://github.com/ksze/django-ses/compare/daa613a4671ed92e8481c9e698d262272b847f9d..87e18abc71ec025a9a11f1069834b2eb73d24269

**Comment by pcraciunoiu** [comment]
Sure, go ahead and open a new PR. Let me know when it's ready so we can avoid back and forth :)
