### ISSUE TITLE
In the handle_bounce view, I got 'eventType' instead of 'notificationType'.

### ISSUE THREAD

**Issue by llloo** [django-ses/django-ses#174]
https://github.com/django-ses/django-ses/blob/af520152c85bfbad6558028c4e662d9256edfe6a/django_ses/views.py#L239

**Comment by znotdead** [comment]
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#top-level-json-object it should be notificationType and I get notification type. But in recent releases it waa changed eventType. Should we add support of both?

**Comment by pcraciunoiu** [comment]
Seems like it! Would you want to open a PR? Looks like there is a test you can copy off of to make sure both work:

https://github.com/django-ses/django-ses/blob/e60d8624ce30a6492101fe8b1cb47448fd55791b/tests/test_views.py#L66

**Comment by znotdead** [comment]
Yeah. will do
