### ISSUE TITLE
InvalidClientTokenId with "AWS_SES_REGION_NAME = 'eu-central-1'"

### ISSUE THREAD

**Issue by gha2012** [django-ses/django-ses#181]
Hi,

I have been using Django-ses for a while and everything worked fine. When I wanted to move out of the ses sandbox, I realised that I had not set the region to "eu-central-1". 

After I did that, I cannot send emails anymore and instead get this error message:
```
boto.exception.BotoServerError: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid.</Message>
  </Error>
  <RequestId>ec8c6de9-9bdc-48ab-8a35-50c8caf4fcd1</RequestId>
</ErrorResponse>
```
Any idea what the problem is? 
Cheers,
Gregor

BTW:
my settings.py looks like this:
```
DEFAULT_FROM_EMAIL = '***@gmail.com'
EMAIL_BACKEND = 'django_ses.SESBackend'
with open('/etc/AWS_ACCESS_KEY_ID.txt') as f:
    AWS_ACCESS_KEY_ID = f.read().strip()

with open('/etc/AWS_SECRET_ACCESS_KEY.txt') as f:
    AWS_SECRET_ACCESS_KEY = f.read().strip()

AWS_SES_REGION_NAME = 'eu-central-1'
AWS_SES_REGION_ENDPOINT = 'email.eu-central-1.amazonaws.com'
```

**Comment by pcraciunoiu** [comment]
Hmm, are you sure the credentials are valid for that region and have SNS access? Is there another software you can use to test them, or maybe try it with boto3 directly? They have good documentation here: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/ses-examples.html

**Comment by starenka** [comment]
maybe the signature version (needs v4 for Frankfurt) comes to play?

https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html
https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

**Comment by gha2012** [comment]
> maybe the signature version (needs v4 for Frankfurt) comes to play?
> 
> https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html
> https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

I have also stumbled upon this during googling around - I don't know how to change it, though...

**Comment by pcraciunoiu** [comment]
Might need to use `host` like here - https://stackoverflow.com/a/29451280

But probably better to upgrade to boto3. I'm not actively using this project, but I'd be happy to take contributions. See also #78

**Comment by TychoVrahe** [comment]
Also having this issue. Credentials are ok (can send with aws-cli2 in eu-central-1) and after switching to us-east-1 it works fine.

**Comment by FoliniC** [comment]
Same problem here... setting "eu-central-1".
When I do 
`python manage.py ses_email_address -l`
I got the invalid token error.
I removed AWS_SES_REGION_NAME and AWS_SES_REGION_ENDPOINT and set 
EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'
the above command worked.
When I try to add my verified email address (ok in AWS console) with
`python manage.py ses_email_address -a info@mydomain.org
Adding email: info@mydomain.org`
I got no errors.
But it didn't work, this verified email is for "eu-central-1" and not for other regions.

Any idea how to solve?

**Comment by kmahelona** [comment]
Same problem. Trying to send to 'ap-southeast-2'. I am able to send email using boto3 and this example https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-python.html. So probably updating to use boto3 will fix it...

**Comment by FoliniC** [comment]
Also updating to boto3 didn't worked for me (eu-central-1)
As a workaround I used us-east-1, repeating domain and email address verification on this region.

I had to wait 3 more days for getting out of sandbox (I asked it for eu-central-1 and us-east-1 so that when the service will work in either region I could switch immediately)

**Comment by GitRon** [comment]
I updated the package to boto3 and now I can send from eu-central-1. Unfortunately some features are not supported the way they used to be. Explicitly proxy for the client and custom dkim signage. Does anyone maybe has the code for this in boto3 at hand?

**Comment by pcraciunoiu** [comment]
I'd think the right path forward is to upgrade dependencies here, though it sounds like that isn't the only needed fix? If anyone would like to contribute... I'd be happy to review and help merge a fix or upgrade.

**Comment by GitRon** [comment]
@pcraciunoiu As I said, I started it but there is a bunch of functionality I'm not using and which has greatly changed in boto3. I think I'd need some help for these cases like proxy and custom dkim.

How shall we proceed?

**Comment by pcraciunoiu** [comment]
You can open a PR against this repo summarizing what's done and what's left, issues... If you post it here, maybe others will be able to help.

**Comment by GitRon** [comment]
@pcraciunoiu Good idea! PR is created and I wrote a list of tasks I see before we can get this going: https://github.com/django-ses/django-ses/pull/183

**Comment by GitRon** [comment]
Btw, any idea why django doesnt find any tests when I call `python manage.py test django_ses`? I added `django_ses` to the installed apps.

**Comment by pcraciunoiu** [comment]
@GitRon You can look at how travis CI runs the tests, for example here: https://github.com/django-ses/django-ses/pull/155

**Comment by GitRon** [comment]
Thanks! Would be nice to debug it but this seems to be impossible this way, right?

**Comment by pcraciunoiu** [comment]
You should be able to run them like so `python runtests.py tests` (see the line in the job I posted) Does that not work?

**Comment by GitRon** [comment]
@pcraciunoiu It works now! At first I used the `tox` command but now I can debug and started fixing the tests 😃
