### ISSUE TITLE
Need to update the signature version for authentication?

### ISSUE THREAD

**Issue by singhravi1** [django-ses/django-ses#184]
Got this email from AWS today.

> Amazon Web Services currently supports Amazon SES API requests that are signed using Signature Version 3 and Signature Version 4 processes. Signature Version 4 further enhances the security around authentication and authorization of Amazon SES customers by using a signing key instead of your secret access key. To improve the security for our customers, beginning October 1, 2020, Amazon Signature Version 3 will be turned off (deprecated) in Amazon SES in favor of Signature Version 4.
> 
> Amazon SES customers who are still using Signature Version 3 must migrate to Signature Version 4 by September 30, 2020. After that, Amazon SES will only accept requests that are signed using Signature Version 4. For more information, see Signature Version 4 signing process [1].
> 
> What Happens if I Don't Make Updates?
> 
> Requests signed with Signature Version 3 that are made after September 30, 2020 will fail to authenticate with Amazon SES. Requesters will see errors stating that the request must be signed with Signature Version 4.
> 
> References:
> [1] https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html
> 

Will this be handled by boto or we'll have to make any change?

**Comment by trecouvr** [comment]
It looks like there is some work going on : https://github.com/django-ses/django-ses/pull/183

**Comment by singhravi1** [comment]
@trecouvr Sounds cool!

There is a note on using signature version 4 signing process,

> If you are using one of the AWS SDKs (including the SDK for C++, SDK for Go, SDK for Java, AWS SDK for JavaScript, AWS SDK for .NET, SDK for PHP, SDK for Python (Boto 3), or SDK for Ruby), you do not have to manually perform the steps of deriving a signing key and adding authentication information to a request. The SDKs perform this work for you. You need to manually sign requests only if you are directly making HTTP or HTTPS requests.

Seems like it should all be fine after we'll be able to update boto to boto3?

**Comment by pcraciunoiu** [comment]
Yes, I'd love to upgrade this project a bit, but haven't had the time... At least I can commit to reviewing and guiding the work. Your contributions are definitely welcome!

**Comment by trecouvr** [comment]
The latest version of django-ses (>1.0.0) tackles this issue using boto3 : https://github.com/django-ses/django-ses/pull/183.
