### ISSUE TITLE
Support for python 2.7.12

### ISSUE THREAD

**Issue by AgDude** [django-ses/django-ses#189]
The recent releases require python 2.7.15 (defined in setup.py).  This causes pip to fail with the message `ERROR: No matching distribution found for django-ses==1.0.1` when attempting to install on python 2.7.12. This has caused some problems for use as we have some environments which still have an older version of python 2.7. Is there any reason this package can't support all versions of python 2.7?

**Comment by pcraciunoiu** [comment]
I don't think there's a reason, if you want to open a PR for that, that'd be great.

For what it's worth, if you can upgrade to python 3, that would be better. Python 2 has reached end of life - https://www.python.org/doc/sunset-python-2/

**Comment by NyanKiyoshi** [comment]
@AgDude I cannot reproduce on Python 3.8.0

What is the output of:
1. `python -c 'import sys; print(sys.version)'`
1. `pip -V`

**Comment by pcraciunoiu** [comment]
Released as 1.0.2: https://pypi.org/project/django-ses/1.0.2/

**Comment by AgDude** [comment]
Thanks for the quick turnaround on the release.
