### ISSUE TITLE
Deprecation warning for django 4.0 for  `providing_args `

### ISSUE THREAD

**Issue by GitRon** [django-ses/django-ses#191]
Hi,

I just saw that we have an upcoming deprecation in this package:

> site-packages\django_ses\signals.py:7: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
  delivery_received = Signal(providing_args=["mail_obj", "delivery_obj", "raw_message"])

Maybe we should tackle this sooner than later 😃 

Best regards  
Ronny

**Comment by pcraciunoiu** [comment]
Would you want to open a PR?

**Comment by GitRon** [comment]
Opened it: https://github.com/django-ses/django-ses/pull/192

**Comment by pcraciunoiu** [comment]
Not planning to make a release just for this... But should be in the next one.

**Comment by GitRon** [comment]
Thanks! And cool with me!
