### ISSUE TITLE
Signature Version 4

### ISSUE THREAD

**Issue by RecNes** [django-ses/django-ses#194]
Hello,

I'm using django_ses as email backend.

Currently;
> django-ses==0.8.5
> boto==2.49.0
> boto3==1.7.24
> botocore==1.10.24

packages are installed on the project, and
```
EMAIL_BACKEND = 'django_ses.SESBackend'
AWS_SES_REGION_NAME = 'eu-west-1'
AWS_SES_REGION_ENDPOINT = 'email.eu-west-1.amazonaws.com'
```
configurations are in the settings.

Should I need to do any changes for avoiding outages of sending emails due to Amazon will moving to signature version 4?

**Comment by NyanKiyoshi** [comment]
You need to upgrade to 1.0+ as it uses boto3 which uses v4. <1.0 is using old boto, which uses a old signature for SES.

**Comment by pcraciunoiu** [comment]
Closing this as upgrading should address any deprecation issues with AWS signature version. If you still have the issue feel free to follow up!

**Comment by SriramChivo** [comment]
Packages & Libraries.

django-ses==2.0.0
boto3==1.9.182
botocore==1.12.200
 
--Class Aws:
        def __init__(self):
           region_name = 'us-east-1'
           self.client = boto3.client(
            service_name='ses',
            region_name=region_name,
            AWS_SES_ACCESS_KEY_ID = settings.AWS_SES_ACCESS_KEY_ID,
            AWS_SES_SECRET_ACCESS_KEY = settings.AWS_SES_SECRET_ACCESS_KEY)

Code accessing the API with emailmessage function from django

email = EmailMessage(
            subject=subject,
            body=message,
            from_email=sender,
            to=receivers,
            **email_kwargs
        )

email_result = email.send(fail_silently=True)

Response:

Signature Version 3 requests are deprecated from March 1, 2021. From that date on, we are progressively rejecting such requests. To resolve the issue you must migrate to Signature Version 4. If you are self-signing your requests, refer to the documentation for Authenticating requests to the Amazon SES API [1] with Signature Version 4 [2]. If you are not self-signing your requests, simply update your SDK/CLI to the latest version. [1] https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html [2] https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

Any Fixes?

**Comment by WDC** [comment]
Can someone help me with this? I have:

```
boto==2.39.0
django-ses>1.0
```

...but I still get this error message when sending:
```
celery_worker_1  |     <Message>Signature Version 3 requests are deprecated from March 1, 2021. From that date on, we are progressively rejecting such requests. To resolve the issue you must migrate to Signature Version 4. If you are self-signing your requests, refer to the documentation for Authenticating requests to the Amazon SES API [1] with Signature Version 4 [2]. If you are not self-signing your requests, simply update your SDK/CLI to the latest version. [1] https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html [2] https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html</Message>
```

I have tried updating `django-ses` and restarting the Docker container, but nothing changes when I go to send outbound SES e-mail messages.

Thanks!

**Comment by WDC** [comment]
@pcraciunoiu do you have any tips for trying to upgrade these libraries to use the new signature version? I have tried _everything_ I can with regards to `pip` and the `requirements.txt` configuration, and I get the above error message every single time. I am running out of options! 

Thanks for your time!
