### ISSUE TITLE
This distribution is not configured to allow the HTTP request method that was used for this request.

### ISSUE THREAD

**Issue by njNafir** [django-ses/django-ses#198]
### I am using django version 3.1.2, with aws ses, I am trying to send email to the customer, in test case my sender and receiver email address is verified, but It returning a error as shown bellow, I thought it causing for localhost server, but I am not sure why this is happening.

\n\n\n\n
403 ERROR
\n
The request could not be satisfied.
\n
\nThis distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.\nWe can\'t connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n
\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n
\n
\n
\nGenerated by cloudfront (CloudFront)\nRequest ID: 74VRxBE8Xv6lMovjGN-DNC5dsylFn7D3gA6ssFFI02JpskGzQC_gAQ==\n
\n
\n
\n

**Comment by floanwelt** [comment]
Hey,
I was having the same issue. For me it is working now and I believe that for me the problem was a wrong AWS_SES_REGION_ENDPOINT.

I changed it to `email.eu-central-1.amazonaws.com` and now it seems to work fine. Maybe that also helps you.

**Comment by njNafir** [comment]
Thanks for your feedback, I used custom code instead of library to solved this problem.
