### ISSUE TITLE
AWS SES Signature V4 : Can't find the request header in the log

### ISSUE THREAD

**Issue by prabath88** [django-ses/django-ses#201]
I was using django-ses 0.8.5 as my email backend and I could see the request header in my application log, which belonged to signature V3. 

`Final headers: {'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'User-Agent': 'Boto/2.49.0 Python/3.7.0 Linux/4.14.209-160.335.amzn2.x86_64', 'Date': 'Sun, 14 Feb 2021 20:32:57 GMT', 'X-Amzn-Authorization': 'AWS3-HTTPS AWSAccessKeyId=AKIEXAMPLEDTA,Algorithm=HmacSHA256,Signature=adWwLkredkdhfhfhhhdhxxxpxKa6o=', 'Content-Length': '44640', 'Host': 'email.us-east-1.amazonaws.com'}`

according to the AWS announcement, they are moving to signature version 4. So I have updated Django-ses 0.8.5 to 1.0.3 latest.

these are my current versions
**django-ses == 1.0.3
boto3 == 1.17.7
botocore=1.20.7**

But, After I update these, I can't see the request header in my application logs to identify the signature version. could you please advise on this?

**Comment by cderickstudy** [comment]
I also upgrade with the same versions and besides that the Amazon Notifier is logging a warning of _Received unknown event_, what I believe is due message.get('eventType') for EmailMultiAlternatives do not have the attribute get.

**Comment by pcraciunoiu** [comment]
It's possible #199 would fix this, if you'd like to give it a try.

**Comment by cderickstudy** [comment]
> It's possible #199 would fix this, if you'd like to give it a try.

Oh cool, yes, my issue is with the handle_bounce :) 
Nice thanks. :)

**Comment by pcraciunoiu** [comment]
Great! If you try out that version from the PR, could you post if you have any other issues or if everything works? Maybe you can review/approve it. I would like to merge it, but I am not currently using this project (just maintaining with all your help!) so it is hard for me to be confident it doesn't break anything.

**Comment by goromachine** [comment]
Hi! is there any update regarding this problem? AWS are going crazy with notifications because I'm using V3 in front of V4.

Thank you!

**Comment by pcraciunoiu** [comment]
@goromachine try out #199 and see if it works for you and fixes issues. If everything looks good, I can merge it and make a release. The holdup has been that we'd like a second person to verify it works.

**Comment by firasslimane** [comment]
Hi! Is there any update soon guys for Signature V4?

Thanks

**Comment by pcraciunoiu** [comment]
@firasslimane try to install the version from #199, and if it works for you we can pull that in and create a release. You can install directly from github:

```
pip install git+https://github.com/cobang/django-ses.git@improve-email-tracking\#egg\=django-ses
```

**Comment by firasslimane** [comment]
I just tried it and the email was sent successfully, but i don't know how to check the signature version.

**Comment by pcraciunoiu** [comment]
You could try to print out the raw message here: https://github.com/django-ses/django-ses/blob/e60d8624ce30a6492101fe8b1cb47448fd55791b/django_ses/views.py#L166

And hopefully see a "SignatureVersion" in the keys.

**Comment by firasslimane** [comment]
I don't use the handle_bounce function, can i detect the signature version with send_messages function on __init__.py

**Comment by pcraciunoiu** [comment]
You might be able to add `signature_version="v4"` in the open method, as one of the arguments to `boto3.client` - https://github.com/django-ses/django-ses/blob/e60d8624ce30a6492101fe8b1cb47448fd55791b/django_ses/__init__.py#L80-L86

Docs: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-the-config-object

**Comment by klloveall** [comment]
I've tried `pip install git+https://github.com/cobang/django-ses.git@improve-email-tracking\#egg\=django-ses` in my deployment and things seem to be fine, although I also don't use handle_bounce function. It does seem to have stopped the flood of SES failure emails about using v4 though. Can this (or at least a fix for the v4 stuff) get merged in soon?

**Comment by pcraciunoiu** [comment]
Released v2.0.0: https://pypi.org/project/django-ses/2.0.0/

Give it a try. Thanks so much for testing!

**Comment by cobang** [comment]
If you experience any problem, try to upgrade`boto3` or migrate from `boto` to `boto3`.

**Comment by zefoo** [comment]
Glad I found this. Just upgraded django-ses to the latest to hopefully stop these nag emails from Amazon! `[Action Required] Migrate to Signature Version 4 to continue using Amazon SES `
