### ISSUE TITLE
Release latest version for django3.2

### ISSUE THREAD

**Issue by awais786** [django-ses/django-ses#212]
We needs the latest the version of django-ses. Master branch has django3.2 support.

Please release latest version for django3.2

**Comment by pcraciunoiu** [comment]
Have you tried to install this on Django 3.2? Because I think it should work. I don't see any changes that would enable that in the last few weeks.

**Comment by pcraciunoiu** [comment]
Released 2.1.0 - https://pypi.org/project/django-ses/2.1.0/
