### ISSUE TITLE
Drop unsupported python (< 3.5) and Django (< 2.2)

### ISSUE THREAD

**Issue by sevdog** [django-ses/django-ses#213]
This project is still tagged and tested with unsupported version of both django and python.

Oldest supported Django version is **`2.2`** branch, which supports python from **`3.5`** onward.

Also python 3.5 is EOL and is not supported by Django 3.x.

https://docs.djangoproject.com/en/3.2/faq/install/#what-python-version-can-i-use-with-django
https://www.python.org/downloads/

**Comment by pcraciunoiu** [comment]
Thanks for filing.

Would you be able to open a PR to fix this?

**Comment by colegatron** [comment]
Any legacy project should not deserve have it working (since there is no real contraindication)?
Just curious, why require Django 2.2 if it just works on 2.1 without issues, including python3.5? (it is my projects case)
I understand this whenever a new feature is added and it stops working on unsupported versions, but why prevent using it beforehand?

**Comment by sevdog** [comment]
> Any legacy project should not deserve have it working (since there is no real contraindication)?
> Just curious, why require Django 2.2 if it just works on 2.1 without issues, including python3.5? (it is my projects case)
> I understand this whenever a new feature is added and it stops working on unsupported versions, but why prevent using it beforehand?

This does not prevent an old project to keep using legacy version, you just have to pin the version 2.0.0 in the requirements file and it will keep working without problems.

Since this is a "plug-in" for Django it would be a problem to keep support for any Django version which is not officially supported by Django-project itself.

**Comment by colegatron** [comment]
The problem with that approach is that can't benefit of any fix after that version. 
For example, AWS SES is sending a complaint notification, the Message object does have a 'notificationType' atribute (as stated on the documentation). In turn, the library is not working for me. After look on the projects issues someone mentioned he received 'eventType' instead 'notificationType'. The library was updated to use it and not it does not works (at least to me) and I need it to support notificationType (as per documentation) instead eventType (maybe it should support both). 
If I pin the version to 2.0.0, I loose the ability to get any fixes.

That is the reason I think that drop support for any version of django or python without having a real issue with them is a very bad idea.

**Comment by sevdog** [comment]
> That is the reason I think that drop support for any version of django or python without having a real issue with them is a bad idea.

Keeping compliancy with any EOL library meas an extra efforts and is a bad habits.

Also keeping an active project which uses an EOL version of Django (which I suppose should be the main framework if you use it) exposes to vulnerabilities which would not be fixed by anyone from the community.

When using opensource software is it important to keep up with support and release cycles, which is also clear from [Django docs](https://docs.djangoproject.com/en/3.2/faq/install/#should-i-use-the-stable-version-or-development-version):

> Generally, if you’re using code in production, you should be using a stable release. The Django project publishes a full stable release every nine months or so, with bugfix updates in between. These stable releases contain the API that is covered by our backwards compatibility guarantees; if you write code against stable releases, you shouldn’t have any problems upgrading when the next official version is released.

Also version X.2 in Django have been defined as [_long term support_](https://www.djangoproject.com/download/#supported-versions) and should be preferred when pinning Django version (also because Django 2.2 it was release in Aprile 2019 and will soon reach is EOL too).

It is up to us developers to keep up with library/framework updates, expecially if we are _willing_ to get any new feature. 

When someone cannot, for any reason, keep up with updated on main branch he can, If he wants to have extra support, build a branch from the version in which there still was compatibility with the old version and work on backporting features.
