### ISSUE TITLE
Error if AWS_SES_AUTO_THROTTLE set to None

### ISSUE THREAD

**Issue by curtismorales** [django-ses/django-ses#218]
If I set `AWS_SES_AUTO_THROTTLE` to `None` in my django settings, I get an error on initializing the SESBackend, I believe because of [this commit](https://github.com/django-ses/django-ses/commit/1a3d387ea4cfc856fee05e17cc457392d7aab190) coercing the setting to a float.

The README [instructs users](https://github.com/django-ses/django-ses#getting-going) to set `AWS_SES_AUTO_THROTTLE` to `None` to turn off automatic throttling, as does a [comment](https://github.com/django-ses/django-ses/blob/master/django_ses/__init__.py#L140)

Looks like this could be fixed by doing this coercion [here](https://github.com/django-ses/django-ses/blob/master/django_ses/__init__.py#L171) or falling back to 0 [here](https://github.com/django-ses/django-ses/blob/master/django_ses/__init__.py#L63)

In case it's helpful to see a traceback:

```
Traceback (most recent call last):                                                                                                                                                                   
  File "/usr/src/app/./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)                                                           
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()                                                                             
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)                                   
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)                                                                                                                                                               
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)                                                                                                                                                           
  File "/usr/src/app/scheduler/management/commands/send_test_email.py", line 24, in handle
    send_email(                                                                                   
  File "/usr/src/app/authapp/utils.py", line 70, in send_email
    email.send()                                                                                  
  File "/usr/local/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])                                                                                                                                    File "/usr/local/lib/python3.9/site-packages/django/core/mail/message.py", line 241, in get_connection
    self.connection = get_connection(fail_silently=fail_silently)
  File "/usr/local/lib/python3.9/site-packages/django/core/mail/__init__.py", line 35, in get_connection
    return klass(fail_silently=fail_silently, **kwds)                                                                                                                                                  File "/usr/local/lib/python3.9/site-packages/django_ses/__init__.py", line 63, in __init__
    self._throttle = float(aws_auto_throttle or settings.AWS_SES_AUTO_THROTTLE)
TypeError: float() argument must be a string or a number, not 'NoneType'   
```

**Comment by curtismorales** [comment]
(Oh and I was able to temporarily work around this by setting `settings.AWS_SES_AUTO_THROTTLE` to 0)

**Comment by pcraciunoiu** [comment]
@curtismorales would you be open to making a PR for this? Could create this type of function and fall back to `None?

https://github.com/mozilla/kitsune/blob/46a8458f0e69245836440abe2b092c279d1eaec7/kitsune/sumo/utils.py#L86

**Comment by lukeburden** [comment]
Hi folks - did an upgrade and hit this issue due to the naive float coercion.

@pcraciunoiu and @curtismorales - looks like the PR for this is close to being done and just needs to be pushed over the line. Any chance you could make some time to complete the thought? It'll save others some hassle for sure.

**Comment by pcraciunoiu** [comment]
Hey Luke,

Thank you for posting.

I'm not actively using this repo now, would you be interested in submitting a fix you can test?

**Comment by pcraciunoiu** [comment]
@lukeburden @curtismorales this has been released as part of v2.5.0 - https://pypi.org/project/django-ses/2.5.0/

@lukeburden I am maintaining the repo, but I'm not actively using the project. It's a good point though, I'll add something to the readme.

**Comment by curtismorales** [comment]
My apologies on not wrapping up this conversation and fix back in August! Thanks @lukeburden for bumping it!

**Comment by lukeburden** [comment]
@pcraciunoiu amazing, thanks for that!

And no worries @curtismorales, thanks for the contribution.
