### ISSUE TITLE
Is AWS SNS message signature still the same?

### ISSUE THREAD

**Issue by hellvix** [django-ses/django-ses#223]
I am doing some debugging in my application, because none of the `signals` is working. Checking the code for `django_ses.views.SESEventWebhookView()` I came across the following:

```
if notification.get('Type') == 'SubscriptionConfirmation':
    self.handle_subscription_confirmation(notification)
elif notification.get('Type') == 'UnsubscribeConfirmation':
    self.handle_unsubscribe_confirmation(notification)
elif notification.get('Type') == 'Notification':
[...]
```

However, from the message example that I got from AWS I cannot see `Type` as a valid dictionary key:

```
{
  "eventType": "Delivery",
  "mail": {
    "timestamp": "2016-10-19T23:20:52.240Z",
    "source": "sender@example.com",
    "sourceArn": "arn:aws:ses:us-east-1:123456789012:identity/sender@example.com",
    "sendingAccountId": "123456789012",
    "messageId": "EXAMPLE7c191be45-e9aedb9a-02f9-4d12-a87d-dd0099a07f8a-000000",
    "destination": [
      "recipient@example.com"
    ],
    "headersTruncated": false,
    "headers": [
      {
        "name": "From",
        "value": "sender@example.com"
      },
      {
        "name": "To",
        "value": "recipient@example.com"
      },
      {
        "name": "Subject",
        "value": "Message sent from Amazon SES"
      },
      {
        "name": "MIME-Version",
        "value": "1.0"
      },
      {
        "name": "Content-Type",
        "value": "text/html; charset=UTF-8"
      },
      {
        "name": "Content-Transfer-Encoding",
        "value": "7bit"
      }
    ],
    "commonHeaders": {
      "from": [
        "sender@example.com"
      ],
      "to": [
        "recipient@example.com"
      ],
      "messageId": "EXAMPLE7c191be45-e9aedb9a-02f9-4d12-a87d-dd0099a07f8a-000000",
      "subject": "Message sent from Amazon SES"
    },
    "tags": {
      "ses:configuration-set": [
        "ConfigSet"
      ],
      "ses:source-ip": [
        "192.0.2.0"
      ],
      "ses:from-domain": [
        "example.com"
      ],
      "ses:caller-identity": [
        "ses_user"
      ],
      "ses:outgoing-ip": [
        "192.0.2.0"
      ],
      "myCustomTag1": [
        "myCustomTagValue1"
      ],
      "myCustomTag2": [
        "myCustomTagValue2"
      ]      
    }
  },
  "delivery": {
    "timestamp": "2016-10-19T23:21:04.133Z",
    "processingTimeMillis": 11893,
    "recipients": [
      "recipient@example.com"
    ],
    "smtpResponse": "250 2.6.0 Message received",
    "reportingMTA": "mta.example.com"
  }
}
```

And indeed, this message is being discarded by the endpoint because it cannot parse the message. Could I have configured something wrong or AWS changed the message signature?

PS: I also get a notification called _AWS Notification Message_ but the signature is also different:

```
{
  "notificationType": "Delivery",
  "mail": {
    "timestamp": "2021-09-09T13:12:13.168Z",
   ...
}
```

**Comment by pcraciunoiu** [comment]
I think the format was changed recently, and now it's `eventType`. We seem to have support for this here https://github.com/django-ses/django-ses/blob/b7a854c791ae4ed82db786cde80732628a7964ae/django_ses/views.py#L235

But perhaps it is incomplete? Would you be able to try this locally and submit a Pull Request to fix the issue? Adding a unit test for it would be good. I think it was updated in #178 and some other PRs following that, but may be incomplete. Unfortunately I am not using this in production right now so it's not easy for me to try it.

Thank you.

**Comment by pcraciunoiu** [comment]
I do think it's confusing AWS has both fields, from what you shared. Check their docs to see what format is meant to be used for which case?

**Comment by hellvix** [comment]
I am receiving both messages, not sure why. I will investigate and eventually create a PR to fix it - along with some tests.
