### ISSUE TITLE
Django 4.1 deprecation warning

### ISSUE THREAD

**Issue by GitRon** [django-ses/django-ses#225]
Hi there!

I just saw a deprecation warning for a future django version. Maybe you could fix it?

> RemovedInDjango41Warning: 'django_ses' defines default_app_config = 'django_ses.apps.DjangoSESConfig'. Django now detects this configuration automatically. You can remove default_app_config.

Thx!
Ronny

**Comment by pcraciunoiu** [comment]
I'm not actively using this, so if you would like to, you could submit a PR and I'm happy to review it.

**Comment by GitRon** [comment]
It's really a great thing that you keep mantaining this package even though you are not using it! ❤️ I'll see if I can fit it.

**Comment by GitRon** [comment]
@pcraciunoiu please have a look at my PR 😃

**Comment by pcraciunoiu** [comment]
Released as 2.2.2 https://pypi.org/project/django-ses/2.2.2/

**Comment by GitRon** [comment]
awesome! thx!
