### ISSUE TITLE
Support of SESv2 client

### ISSUE THREAD

**Issue by lskbr** [django-ses/django-ses#229]
SESv2 client (boto3/AWS) supports unsubscribe links and adds a new SQS event type.
This event tracks email provider options/buttons to unsubscribe from an email list.

**Comment by dimaMatveev** [comment]
Has anyone added SESv2 support?

**Comment by pcraciunoiu** [comment]
Not that I know of, you're welcome to open a PR. I haven't looked into it, if it's builtin to boto3 it shouldn't be too difficult?

**Comment by pcraciunoiu** [comment]
Fixed in #269
