### ISSUE TITLE
Thanks! Finally deployed.

### ISSUE THREAD

**Issue by mlissner** [django-ses/django-ses#245]
Just a note to say thanks for the great package. We finally deployed v3.0.1 in CourtListener.com yesterday evening, and have used it to send 600 emails so far. We also hooked up the webhook endpoint and are collecting bounces and other notifications that we weren't able to get when we were self-hosting our email using postfix. So far, we've identified ten email addresses that we've been sending emails to that are dead! 

Anyway, I'm loving this system, and very appreciative of it. Thank you for continuing to maintain it. 

(Closing this issue so you don't have to log in.)

**Comment by pcraciunoiu** [comment]
I appreciate your gratitude Mike!
