### ISSUE TITLE
Receive emails

### ISSUE THREAD

**Issue by fabge** [django-ses/django-ses#257]
It would be great if django-ses would allow to also receive emails.
As far as I understand it, after setting up SNS, the only thing that is missing is adding another signal analog to the existing ones:

```python
bounce_received = Signal()
complaint_received = Signal()
delivery_received = Signal()
send_received = Signal()
open_received = Signal()
click_received = Signal()
```

Something like `mail_received`?

**Comment by pcraciunoiu** [comment]
Hey, you are welcome to open a pull request for this and test it on your project. I can review the code.

**Comment by alexandernst** [comment]
I'm interested in this feature 🤔
@pcraciunoiu can I pick it up?

**Comment by pcraciunoiu** [comment]
@alexandernst sure thing. Thanks!

**Comment by alexandernst** [comment]
This can get closed :)
