### ISSUE TITLE
Support newer versions of cryptography and requests for events extra

### ISSUE THREAD

**Issue by jasonhernandez** [django-ses/django-ses#262]
It looks like the events extra requires cryptography version 36.0.2 and requests version 2.27.1. Ideally this package would support newer versions of both libraries.

I'm running into this because Daphne 4.0 requires cryptography >= 37.0.0 and I'm running into conflicts between it and django-ses[events]

What's the process for supporting newer versions of these libraries? Does someone (possibly me) just need to run tests.py with some newer versions of cryptography (37.x and 38.x) and submit a pull request to loosen the requirements in pyproject.toml?

**Comment by pcraciunoiu** [comment]
@jasonhernandez yes, that sounds right. I didn't closely pay attention that it's pinned to a major version, so I think loosening requirements to >= 36 would be fine if unit tests pass and the library works for you in a manual test. Thanks for filing!

**Comment by jasonhernandez** [comment]
Thanks for the quick response @pcraciunoiu. I need to do a bit of work on my end before I'm able to test this in my application because I haven't implemented this functionality (but it's on my roadmap), and also need to learn a few things before I can patch this. I'll probably take a crack at this in a week or two unless someone else beats me to it.

**Comment by pcraciunoiu** [comment]
@OndraRehounek do you want to open a new PR for `requests` also?

**Comment by OndraRehounek** [comment]
@pcraciunoiu I can do another PR on Monday for `requests`. I was considering do it in one PR but `cryptography` seemed to be much urgent issue

**Comment by OndraRehounek** [comment]
@pcraciunoiu it is working perfectly, thank you :) I opened similar PR for requests
