### ISSUE TITLE
Where does one set up handlers?

### ISSUE THREAD

**Issue by sid-hant** [django-ses/django-ses#293]
This is a dumb question but for example, where would I add the following code in my code base?

```
from django_ses.signals import send_received
from django.dispatch import receiver


@receiver(send_received)
def send_handler(sender, mail_obj, raw_message,  *args, **kwargs):
    ...
```

**Comment by pcraciunoiu** [comment]
Anywhere I guess?

You could add it to your app's `signals.py` or something similar, like `emails.py`, and make sure that file is imported.

You can read some ideas here too https://docs.djangoproject.com/en/4.2/topics/signals/

**Comment by sid-hant** [comment]
> Anywhere I guess?
> 
> 
> 
> You could add it to your app's `signals.py` or something similar, like `emails.py`, and make sure that file is imported.
> 
> 
> 
> You can read some ideas here too https://docs.djangoproject.com/en/4.2/topics/signals/

Thanks! when you say it's imported, where would i need to import the file?

**Comment by pcraciunoiu** [comment]
> Thanks! when you say it's imported, where would i need to import the file? 

You could do it in your app's init.py, but it depends how you organize your code. I'm sure you can do an internet search for organizing your djabgo codebase with signals, too.
