### ISSUE TITLE
Issue with Downloading - Long Wait Time

### ISSUE THREAD

**Issue by blazstefin** [django-ses/django-ses#308]
I am experiencing a significant delay when attempting to download django-ses The download process has been ongoing for approximately 15 minutes without completion. This issue persists even after manually installing boto.

This is the url of package:

https://files.pythonhosted.org/packages/e4/e6/f41a1936b7602d9badb66ae9677e5d4cfc8bd9955a9a1618a0945f2f5b1b/botocore-1.19.27-py2.py3-none-any.whl

**Comment by pcraciunoiu** [comment]
Hey @blazstefin this is instant on my computer, and at any rate it's a pip issue not a package issue. Try VPN or using a different network?

**Comment by blazstefin** [comment]
Hey @pcraciunoiu ,

Thank you for the advice provided. Unfortunately, the issue still persists, and I have some additional information that might help in diagnosing the problem:

I'm using Poetry for dependency management, and the issue happens when I run the command poetry add django-ses. Here's what happens:

The command starts resolving dependencies and begins downloading botocore-1.15.34.
The download process seems to loop indefinitely. It progresses to 100%, then restarts repeatedly without ever completing.
I observed this behavior at the following URL: https://files.pythonhosted.org/packages/d3/e5/a17b433744375c43b92b1a79eb1795770ebbdb5a0f3edcd89f1b9c9f73ca/botocore-1.15.34-py2.py3-none...

I have not encountered similar issues with other packages using Poetry.

Is this a known issue with Poetry's dependency resolution, or could it be specific to the django-ses package's dependencies?
 
Any guidance or alternative solutions to successfully add django-ses would be greatly appreciated.

**Comment by blazstefin** [comment]
Hey @pcraciunoiu,

Just wanted to give you an update, I have successfully resolved the issue. The solution was to manually install botocore first. After doing that, django-ses installation was successfull.
