### ISSUE TITLE
pypi points to old repo

### ISSUE THREAD

**Issue by JeffAbrahamson** [django-ses/django-ses#312]
At https://pypi.org/project/django-ses3/
the "home page" link points to
http://github.com/tricoder42/django-ses/
instead of to this repo.

**Comment by pcraciunoiu** [comment]
django-ses3 is not this repo and is not under my control. You can see this is the maintainer, it's probably an unofficial fork
from 10 years ago
https://pypi.org/user/elvard/

**Comment by pcraciunoiu** [comment]
@JeffAbrahamson if you want to have it removed, it should be an issue in the other repo, not this one

**Comment by JeffAbrahamson** [comment]
Good point, I missed the 3.  Sorry.

Probably hard to file an issue on the no longer existing other repository. ;-)
And the pypi maintainer, elvard, seems no longer reachable...
