### ISSUE TITLE
Would you accept a Blacklist feature?

### ISSUE THREAD

**Issue by alexandernst** [django-ses/django-ses#330]
Hi!

A very common use case for SES / SNS is to handle the bounce and the complaints events and add the recipients to a "blacklist" so that they won't receive any future emails (as they would just cause a bounce or a rejection, in the case of recipients who have issued a complaint).

This use case can be handled with a very small amount of code: a single model with 1 field that will hold the blacklisted email, a couple of lines that will subscribe to the bounce and complaint signals and a few lines in the `EmailBackend` implementation that will skip sending the email if the recipient has been previously blacklisted.

The feature could be configurable via `AWS_SES_ENABLE_BOUNCE_BLACKLIST` and `AWS_SES_ENABLE_COMPLAINT_BLACKLIST`.

Would you be interested in such a feature if I were to submit a PR?

Regards

**Comment by pcraciunoiu** [comment]
Would consider this feature yes. Can you find any other libraries that integrate with SES and support this? That could be a good model for how it might be added here.

The feature should be off by default. I believe we already provide a way to handle bounce notifications, so need to make sure that remains.

**Comment by alexandernst** [comment]
Hi @pcraciunoiu ! Thanks for the reply. I couldn't find any other libs that support this, but I have been using my own code for years. The "Blacklisted" model has a single field (the email), the code that parses the complaints and debounce objects has ~25 lines and that's pretty much it. I can attach it right here if you want to have a look at it before I start with the PR.

**Comment by pcraciunoiu** [comment]
Sure, I can take a look @alexandernst

**Comment by alexandernst** [comment]
The model could look like this:

```python
class BlacklistedEmail(models.Model):
    email = models.EmailField(max_length=255, unique=True)

    def __str__(self):
        return self.email
```

And, when the feature is enabled, we'd need to attach these signal handlers:

```python
from .utils import (
  get_permanent_bounced_emails_from_bounce_obj,
  get_emails_from_complaint_obj,
)

@receiver(bounce_received)
def bounce_handler(sender, mail_obj, bounce_obj, raw_message, *args, **kwargs):
  bounced_recipients = get_permanent_bounced_emails_from_bounce_obj(bounce_obj)
  for email in bounced_recipients:
    models.BlacklistedEmail.objects.get_or_create(email=email.lower())

@receiver(complaint_received)
def complaint_handler(sender, mail_obj, complaint_obj, raw_message, *args, **kwargs):
  complaint_emails = get_emails_from_complaint_obj(complaint_obj)
  for email in complaint_emails:
    models.BlacklistedEmail.objects.get_or_create(email=email.lower())
```

The `utils.py`:

```python
from email.utils import parseaddr
from . import models

def get_permanent_bounced_emails_from_bounce_obj(bounce_obj: dict) -> list:
    """Extracts permanent bounced email addresses only as a list of strings.
    https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#bounce-object
    """
    bounced_recipients = bounce_obj.get("bouncedRecipients", list())
    return [br.get("emailAddress") for br in bounced_recipients if br.get("status").startswith("5")]


def get_emails_from_complaint_obj(complaint_obj: dict) -> list:
    """Extracts complaint email addresses from complaint_obj
    https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#complaint-object
    """
    return [cr.get("emailAddress") for cr in complaint_obj.get("complainedRecipients", list())]

def filter_blacklisted_recipients(addresses):
    """Remove blacklisted emails from addresses"""
    if type(addresses) is str:
        addresses = [addresses]

    filtered_addresses = []
    for recipient in addresses:
        addr = parseaddr(recipient)[1].lower()
        if models.BlacklistedEmail.objects.filter(email=addr).exists():
            continue
        filtered_addresses.append(recipient)
    return filtered_addresses
```

And finally, the backend should be patched like this:

```python
    def send_messages(self, email_messages):
        if not email_messages:
            return

        for email_message in email_messages:
            email_message.to = filter_blacklisted_recipients(email_message.to)
            email_message.cc = filter_blacklisted_recipients(email_message.cc)
            email_message.bcc = filter_blacklisted_recipients(email_message.bcc)

    # TODO: Maybe check if len(to) + len(cc) + len(bcc) == 0, in which case just exit

    <the rest of the code>
```

IMHO all that this is missing is to integrate it inside django-ses and wrap it in a few `if`s that would make this feature configurable via settings.

What do you think?

**Comment by pcraciunoiu** [comment]
Thanks for sharing. This makes sense to me, so long as we don't affect existing functionality and make it configurable!

**Comment by alexandernst** [comment]
Great! Let me see if I can find a little bit of spare time and do a PR :)

**Comment by alexandernst** [comment]
@pcraciunoiu ^ I think this is in a good enough shape to be peer reviewed 🙏
