### ISSUE TITLE
When sending multiple emails, if a single email has all recipients blacklisted, all subsequent emails are discarded

### ISSUE THREAD

**Issue by ezet** [django-ses/django-ses#341]
When using SESBackend.send_messages(), the function returns when it encounters a single message where all recipients are blacklisted. I would expect that only the single message is discarded, not all remaining emails.

https://github.com/django-ses/django-ses/blob/2750389580bac80645060db5528cf38a4a6c46fc/django_ses/__init__.py#L142-L144

**Comment by pcraciunoiu** [comment]
Fixed in #342.

Released in v4.3.1:

https://pypi.org/project/django-ses/4.3.1/
