### ISSUE TITLE
Support for Python 3?

### ISSUE THREAD

**Issue by maryokhin** [django-ses/django-ses#64]
Interested if there is support for `Python 3` and `Django 1.7`?

**Comment by leandropls** [comment]
I'm interested in Python 3 support.

**Comment by edwinlunando** [comment]
Hi! I'm waiting for Python 3 support too.

**Comment by Zeioth** [comment]
Waiting for Python 3 sup too.

**Comment by troygrosfield** [comment]
#68 and #69 have been merged.  This lib now supports python 3 via master until the next official release.  Closing this issue.
