### ISSUE TITLE
PyPi Release

### ISSUE THREAD

**Issue by adamcharnock** [django-ses/django-ses#70]
I've seen this mentioned in a few other places, but I though I'd raise a specific issue for it. Could a PyPi release be done for the project? I'm currently pulling in from GitHub in order to get Python 3 support.

Am I right in thinking @pcraciunoiu has permission to do this?

**Comment by pcraciunoiu** [comment]
I've mostly passed responsibilities to tswicegood and jschneier at this point...

Here's the PyPi role information:

<pre>Existing Roles
User	    Role
hmarr	    Owner
tswicegood	Maintainer
embrangler	Maintainer
tswicegood	Owner
embrangler	Owner
jschneier	Maintainer</pre>

**Comment by kezabelle** [comment]
I'd be keen to see a Py3K release too, fwiw.

**Comment by muhammad-ammar** [comment]
@tswicegood Can you please make a new release of latest code for PyPi so that people can use Python3 support. Thanks

**Comment by benf-wspdigital** [comment]
The release 0.8.0 is *described* at PyPI (https://pypi.python.org/pypi/django-ses/0.8.0) but the code is not released there.

Please add the files needed (the sdist, and the wheel) to install the library directly from PyPI using Pip.

**Comment by pcraciunoiu** [comment]
I believe that's all been done now. I don't release on pypi often so I forget the upload step, sorry about that. Looks like people use twine or `setup.py sdist bdist_wheel upload`, but I had to figure that out doing a search.

**Comment by benf-wspdigital** [comment]
Thank you for the quick response! That works fine now.
