### ISSUE TITLE
Support for Django 1.8

### ISSUE THREAD

**Issue by muzaffaryousaf** [django-ses/django-ses#72]
Does this support Django 1.8. I have not seen anything related to that. Do you have any plans to add the support, if yes when it will be up.
Thanks.

**Comment by craigbruce** [comment]
The tests [run](https://travis-ci.org/django-ses/django-ses) with Django 1.8 and I run multiple sites on 1.8 - so yes.

**Comment by muzaffaryousaf** [comment]
ah thats a big relief. Thanks a lot @craigbruce
