### ISSUE TITLE
Support for "IAM roles for EC2"

### ISSUE THREAD

**Issue by lyn5466** [django-ses/django-ses#80]
Hi guys,

Is it possible to make this package support ["IAM roles for EC2"](http://aws.amazon.com/about-aws/whats-new/2012/06/11/Announcing-IAM-Roles-for-EC2-instances/) feature?

I think the workable change would be something like below:

**_Orginal**_

```
connection = SESConnection(
                aws_access_key_id=access_key_id,
                aws_secret_access_key=access_key,
                region=region)
```

**_Support for IAM**_

```
connection = boto.ses.connect_to_region(region=region) If aws_access_key_id is None or aws_secret_access_key is None else boto.ses.connect_to_region(aws_access_key_id=access_key_id, aws_secret_access_key=access_key, region=region)
```

**Comment by tylerneu** [comment]
I too thought that IAM roles were not supported when I had mistakenly defined associated environment variables or Django settings. Removing these allowed `boto` to use shared credentials.

I recommend increasing the verbosity of logging with something like the following snippet to see what `boto`.

`LOGGING = {
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'boto': {
            'handlers': ['console'],
            'level': 'DEBUG',
        }
    }
}`

`[06/Apr/2016 15:53:51] DEBUG [boto:301] Using access key found in shared credential file.
[06/Apr/2016 15:53:51] DEBUG [boto:327] Using secret key found in shared credential file.`

**Comment by reedloden** [comment]
This works fine if you just leave the keys blank. boto will search for credentials elsewhere (including instance profiles), and will work fine. So, think this can be closed out.

**Comment by pcraciunoiu** [comment]
Hey, I know you from Mozilla days @reedloden -- thanks for pitching in. Closing :)
