### ISSUE TITLE
except SESConnection.ResponseError, err: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by psnma** [django-ses/django-ses#87]
I am using Django 1.9 and Python 3. When runserver:

File "/Users/abc/.virtualenvs/project/lib/python3.4/site-packages/django_ses/**init**.py", line 173
    except SESConnection.ResponseError, err:
                                      ^
SyntaxError: invalid syntax

**Comment by rluedeman** [comment]
I think it's just an issue with the package that's on https://pypi.python.org/pypi/django-ses. It claims to be django_ses version 0.7, but if you crack open https://pypi.python.org/packages/source/d/django-ses/django-ses-0.7.0.tar.gz#md5=da730a7571b7a94bbd69ccd70b7e8bed, it show's version=0.6. Can someone upload the most recent version of django_ses to pypi?

**Comment by pcraciunoiu** [comment]
Released [on pypi](https://pypi.python.org/pypi?name=django-ses&version=0.7.1&:action=display) as 0.7.1

You may update your packages and follow up here if you're still seeing the issue.

**Comment by psnma** [comment]
I tried to install and could not:

(myenv)iMac:myproject paulo$ pip3 install django-ses==0.7.1
Could not find a version that satisfies the requirement django-ses==0.7.1 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.6.0, 0.7.0)
No matching distribution found for django-ses==0.7.1

**Comment by hornedbull** [comment]
I've the same issue. Is this resolved yet? I'm still only seeing 0.7.0 as the latest version.

**Comment by pcraciunoiu** [comment]
Probably because I forgot to upload the dist. Sorry. Check now.
