### ISSUE TITLE
0.7.1 doesn't show-up nor install in pip

### ISSUE THREAD

**Issue by Bartvds** [django-ses/django-ses#89]
0.7.1 is listed on pypi: https://pypi.python.org/pypi/django-ses/0.7.1  for a few weeks now.

I tried installing it with python 3.5 on ubuntu, using pip 8.1.1 but I keep getting this error:

> Could not find a version that satisfies the requirement django-ses==0.7.1 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.6.0, 0.7.0)

I tried --no-cache-dir and then just removing ~/.cache/pip altogether. I also tried installing on a few other machines but none of their pip's can see 0.7.1.

**Comment by Bartvds** [comment]
I checked the pypi JSON feed: https://pypi.python.org/pypi/django-ses/json and it looks a bit funky: in the list of versions the 0.7.1 element is empty:

![django-ses](https://cloud.githubusercontent.com/assets/685984/14465191/552380d8-00d2-11e6-95e6-62bfa3978ad5.png)

**Comment by pcraciunoiu** [comment]
@Bartvds thanks for pointing that out. I believe I had forgotten to upload the distribution. Should work now.

**Comment by Bartvds** [comment]
Cool, I just retried and it installs correctly now.

Thanks for your quick fix! :+1:
