### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by krisys** [django-ses/django-ses#90]
I see that this app does not include the initial migrations. Is this intentional or am I missing something here?

**Comment by pcraciunoiu** [comment]
`syncdb` should do it
https://github.com/django-ses/django-ses#store-daily-stats

**Comment by michaelhelmick** [comment]
This is an issue because `syncdb` was deprecated in Django 1.7 and removed in Django 1.9.

The alternative is running: `./manage.py migrate --run-syncdb`

**Comment by pcraciunoiu** [comment]
Thanks @michaelhelmick

**Comment by krisys** [comment]
Thanks @michaelhelmick
