### ISSUE TITLE
Region settings are not strictly optional

### ISSUE THREAD

**Issue by proog** [django-ses/django-ses#94]
The readme says "additionally, you can specify an optional region". However, if you are outside the default region (which I think is us-east-1), AWS_SES_REGION_NAME and AWS_SES_REGION_ENDPOINT are required. Sending emails will fail with an unhelpful "Address not verified" error if these are omitted.

In my opinion, a quick mention of this case would improve the readme.

**Comment by pcraciunoiu** [comment]
@proog if you want to make that a PR, I'm happy to merge it in.
