### ISSUE TITLE
DKIM signing steps in README unnecessary when enabled in SES

### ISSUE THREAD

**Issue by Bartvds** [django-ses/django-ses#96]
Not sure why the section on DKIM is in the README, maybe it is an artifact from earlier?

Anyway, if you enable DKIM in the SES Console (and go through the verification steps) then Amazon will apply the DKIM signing (so you don't need the hassle with the keys).

**Comment by pcraciunoiu** [comment]
@Bartvds if you open a PR updating the README (and linking to external sources if it helps others), I'm happy to merge it in.

**Comment by Bartvds** [comment]
:+1:
